# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["<oss@fastly.com>"]
description = "A project for learning about edge computing."
language = "javascript"
manifest_version = 3
name = "Hello Compute"

[local_server]

  [local_server.backends]

    [local_server.backends.website]
      override_host = "glitchdotcom.github.io"
      url = "https://glitchdotcom.github.io/"

[scripts]
  build = "npm run build"
  post_init = "npm install"

[setup]

  [setup.backends]

    [setup.backends.website]
      address = "glitchdotcom.github.io"
